# Generated by Django 4.0.6 on 2022-08-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_categorias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
